# Generated by Django 6.0.6 on 2026-09-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('VETERINARIO', 'Veterinario'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=20, verbose_name='Rol'),
        ),
    ]
