# Generated by Django 6.1.1 on 2026-09-25 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la mascota')),
                ('especie', models.CharField(max_length=50, verbose_name='Especie (Ej. Perro, Gato)')),
                ('raza', models.CharField(blank=True, max_length=50, verbose_name='Raza')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('propietario', models.ForeignKey(limit_choices_to={'rol': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL, verbose_name='Dueño')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento recetado')),
                ('notas_adicionales', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('veterinario', models.ForeignKey(limit_choices_to={'rol': 'VETERINARIO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atendido por')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='usuarios.mascota', verbose_name='Mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora de la cita')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo de la consulta')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=15, verbose_name='Estado')),
                ('veterinario', models.ForeignKey(limit_choices_to={'rol': 'VETERINARIO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Veterinario asignado')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='usuarios.mascota', verbose_name='Mascota')),
            ],
        ),
    ]
